# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d9b8b742ac1f0fd379e254bcb0e700b32129f3dd98a151a9e45cba60bfd7d57ced0b0461242d3785dc2db077cf153c680c165b01efc605e10752b18107e9723

test:
  secret_key_base: 16678f411b39216c82576874b429e09e6b8a212b6ff8c557365c6157d1daf92e657f282bd032cb0f268fbb73ba7590936f4f9cc8db6eb32fff33da0f63cb7d4c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
